### ISSUE TITLE
Call to os.getlogin() fails on linux

### ISSUE THREAD

**Issue by jflann** [kegsmr/sc4mp-server#5]
Server won't run on xubuntu due to exception from os.getlogin().  Python docs recommend using getpass.getuser() see [https://bugs.python.org/issue40821](https://bugs.python.org/issue40821).  I've tested this and it seems to work.

**Comment by kegsmr** [comment]
Hi, thanks for the report. This problem should now be fixed in the version 0.3.1 release of the SC4MP Server.
